# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-03-15 12:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(verbose_name='Content')),
                ('date', models.DateTimeField(verbose_name='Time')),
                ('iscompleted', models.BooleanField(default=False, verbose_name='Is Completed')),
                ('isEmailSent', models.BooleanField(default=False, verbose_name='Is Email Sent')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
        ),
    ]
