# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-03-14 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_auto_20200130_0512'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='isEmailSent',
            field=models.BooleanField(default=False, verbose_name='Is Email Sent'),
        ),
    ]
