# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-03-14 20:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0010_auto_20200202_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='articleImage',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Resim Ekle/Add Picture'),
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='article',
            name='createdDate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Title'),
        ),
    ]
