# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-03 22:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0005_auto_20200201_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='userImage',
            field=models.ImageField(blank=True, null=True, upload_to=b'', verbose_name='Resim Ekle/Add Picture'),
        ),
    ]
