# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-04 01:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0011_auto_20200204_0344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='userImage',
        ),
        migrations.AddField(
            model_name='comment',
            name='comments2',
            field=models.TextField(blank=True, max_length=4000, null=True, verbose_name='Yorum Ekle'),
        ),
    ]
